### ISSUE TITLE
ERROR in TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kiewic** [angular-seattle/agora#2]
Running `ng serve` I am getting the following error:

    ERROR in TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:12619:109)
    at parseSourceFileWorker (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:12551:26)
    at Object.parseSourceFile (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:12477:26)
    at Object.createSourceFile (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:12318:29)
    at VirtualFileStats.getSourceFile (/Users/gilberto/repos/agora/node_modules/@ngtools/webpack/src/compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile (/Users/gilberto/repos/agora/node_modules/@ngtools/webpack/src/compiler_host.js:206:38)
    at findSourceFile (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70782:29)
    at processImportedModules (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70949:25)
    at findSourceFile (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70830:17)
    at processImportedModules (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70949:25)
    at findSourceFile (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70830:17)
    at args (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70719:85)
    at getSourceFileFromReferenceWorker (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70692:34)
    at processSourceFile (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70719:13)
    at processRootFile (/Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:70573:13)
    at /Users/gilberto/repos/agora/node_modules/typescript/lib/typescript.js:69765:60

I am running it on Mac. I only ran `npm i` before `ng serve`, did I miss something?

**Comment by heathkit** [comment]
As you discovered, this is because environment.ts is missing, and there's no documentation telling people they need to create one and add the credentials for their test environment to it.
